load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Data",
    srcs = ["Contract.swift"],
    module_name = "Data",
    visibility = ["//App:__subpackages__"],
)
